version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0
  
jobs:
  lint-and-test:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make setup
            source ~/.sayhello/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            source ~/.sayhello/bin/activate
            make lint 
      - run:
          name: Test App
          command: |
            source ~/.sayhello/bin/activate
            make test 
  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            # Replace the placeholders in the manifest with the intended values.
            # This is to avoid hardcoding the image name in the manifest, to make this
            # demo project more portable.
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/demo-app-deployment.yaml.template |\
               sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>|\
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE|\
                << parameters.version-info >>|g" > deployment/demo-app-deployment.yaml
      - run:
          name: See deployment manifest
          command: |
            cat deployment/demo-app-deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/demo-app-deployment.yaml"
          get-rollout-status: true
          resource-name: deployment/flask-app
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/demo-app-service.yaml"
  test-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - run:
          name: Wait for service to be ready
          command: |
            kubectl get pods
            kubectl get services
            sleep 30
            for attempt in {1..20}; do
              EXTERNAL_IP=$(kubectl get service flask-app | awk '{print $4}' | tail -n1)
              echo "Checking external IP: ${EXTERNAL_IP}"
              if [ -n "${EXTERNAL_IP}" ] && [ -z $(echo "${EXTERNAL_IP}" | grep "pending") ]; then
                break
              fi
              echo "Waiting for external IP to be ready: ${EXTERNAL_IP}"
              sleep 10
            done
            sleep 180
            echo "External IP: ${EXTERNAL_IP}" 
            curl -s --retry 10 "http://$EXTERNAL_IP:5000" | grep "Say Hello"
workflows:
  deploy-pipeline:
    jobs:
      - lint-and-test
      #- aws-eks/create-cluster:
      #    cluster-name: alex-cluster
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          path: .
          region: AWS_DEFAULT_REGION
          repo: flask-udacity
          tag: "$CIRCLE_SHA1"
          requires: 
            - lint-and-test
      - deploy-application:
          cluster-name: alex-cluster
          aws-region: $AWS_DEFAULT_REGION
          docker-image-name: "${AWS_ECR_ACCOUNT_URL}/flask-udacity:${CIRCLE_SHA1}"
          version-info: "${CIRCLE_SHA1}"
          requires:
            - aws-ecr/build_and_push_image
          #  - aws-eks/create-cluster
      - test-application:
          name: test-application
          cluster-name: alex-cluster
          aws-region: $AWS_DEFAULT_REGION
          requires:
            - deploy-application
