# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  lint-and-test:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make setup
            source ~/.sayhello/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      # run lint!
      - run:
          name: run lint
          command: |
            source ~/.sayhello/bin/activate
            make lint 

  build-image:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_DEFAULT_REGION
          repo: public.ecr.aws/v0u2j1d8/flask
          tag: "$CIRCLE_SHA1"

workflows:
  dev-flow:
    jobs:
      - lint-and-test
      - build-image
          requires: [lint-and-test]
  