# Python CircleCI 2.0 configuration file
# Hola
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
orbs:
  aws-ecr: circleci/aws-ecr@x.y.z
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: WS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_DEFAULT_REGION
          repo: public.ecr.aws/v0u2j1d8/flask
          tag: "$CIRCLE_SHA1"