apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      nodePort: 5000
      protocol: TCP